### ISSUE TITLE
Can't start server.

### ISSUE THREAD

**Issue by moayman** [Sology/azure_direct_upload#1]
Hello I am getting this as I "rails server":

/home/asalah/.rvm/gems/ruby-2.2.2/gems/azure_direct_upload-0.0.1/lib/azure_direct_upload/railtie.rb:4:in `block in <class:Railtie>': uninitialized constant AzureDirectUpload::Railtie::JQuery (NameError)
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:30:in`instance_exec'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /home/asalah/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    from /home/asalah/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in`block (2 levels) in each_strongly_connected_component'
    from /home/asalah/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    from /home/asalah/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in`block in each_strongly_connected_component'
    from /home/asalah/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
    from /home/asalah/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in`call'
    from /home/asalah/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    from /home/asalah/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in`tsort_each'
    from /home/asalah/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:54:in`run_initializers'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
    from /home/asalah/daleelak/config/environment.rb:5:in`<top (required)>'
    from /home/asalah/daleelak/config.ru:3:in `block in <main>'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in`instance_eval'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
    from /home/asalah/daleelak/config.ru:in`new'
    from /home/asalah/daleelak/config.ru:in `<main>'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:49:in`eval'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:40:in`parse_file'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:208:in`app'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/server.rb:61:in `app'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:336:in`wrapped_app'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/server.rb:139:in `log_to_stdout'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/server.rb:78:in`start'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:80:in `block in server'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in`tap'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `server'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
    from /home/asalah/daleelak/bin/rails:8:in`require'
    from /home/asalah/daleelak/bin/rails:8:in `<top (required)>'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/client/rails.rb:28:in`load'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `call'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/client/command.rb:7:in`call'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/client.rb:26:in `run'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/bin/spring:48:in`<top (required)>'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/binstub.rb:11:in `load'
    from /home/asalah/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/binstub.rb:11:in`<top (required)>'
    from /home/asalah/daleelak/bin/spring:13:in `require'
    from /home/asalah/daleelak/bin/spring:13:in`<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in`<main>'

**Comment by keyeh** [comment]
In your Gemfile, add:

```
gem 'jquery-rails'
gem 'jquery-fileupload-rails'
```

above 

`gem "azure_direct_upload"`
